# Generated by Django 6.0.3 on 2026-03-15 00:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.CharField(db_index=True, max_length=3)),
                ('quote_currency', models.CharField(db_index=True, max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=14)),
                ('fetched_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'exchange_rates',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
