# Generated by Django 5.2.3 on 2026-03-20 07:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0004_friendinvite"),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_expense_created', models.BooleanField(default=True)),
                ('push_settlement_recorded', models.BooleanField(default=True)),
                ('push_group_invitation', models.BooleanField(default=True)),
                ('email_expense_created', models.BooleanField(default=True)),
                ('email_settlement_recorded', models.BooleanField(default=True)),
                ('email_weekly_digest', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to='users.user')),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=500, unique=True)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='users.user')),
            ],
            options={
                'db_table': 'device_tokens',
                'indexes': [models.Index(fields=['user'], name='device_toke_user_id_25a987_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('expense_created', 'New expense added'), ('expense_deleted', 'Expense deleted'), ('settlement_recorded', 'Payment recorded'), ('settlement_confirmed', 'Payment confirmed'), ('group_invitation', 'Group invitation'), ('member_added', 'Added to group'), ('weekly_digest', 'Weekly balance digest')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=500)),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triggered_notifications', to='users.user')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='users.user')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_2c3905_idx')],
            },
        ),
    ]
