# Generated by Django 5.2.3 on 2026-03-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_weekly_digest',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('expense_created', 'New expense added'), ('expense_deleted', 'Expense deleted'), ('settlement_recorded', 'Payment recorded'), ('settlement_confirmed', 'Payment confirmed'), ('group_invitation', 'Group invitation'), ('member_added', 'Added to group')], max_length=50),
        ),
    ]
