# Generated by Django 6.0.3 on 2026-03-15 00:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0002_initial'),
        ('users', '0003_restore_full_user_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_owed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('share_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('is_settled', models.BooleanField(default=False)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splits', to='expenses.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splits', to='users.user')),
            ],
            options={
                'db_table': 'splits',
                'ordering': ['created_at'],
            },
        ),
    ]
