# Generated by Django 6.0.3 on 2026-03-14 17:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("supabase_uid", models.UUIDField(unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("avatar_url", models.TextField(blank=True, null=True)),
                ("preferred_locale", models.CharField(default="pt_BR", max_length=10)),
                ("default_currency", models.CharField(default="BRL", max_length=3)),
                ("is_ad_free", models.BooleanField(default=False)),
                ("stripe_customer_id", models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
    ]
