# Generated by Django 5.2.3 on 2026-03-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_friendinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="plan_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="plan_type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
