# Generated by Django 6.0.3 on 2026-03-15 00:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_restore_full_user_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('exchange_rate_to_group_currency', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=14)),
                ('amount_in_group_currency', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(default='geral', max_length=50)),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate)),
                ('split_method', models.CharField(choices=[('equal', 'Equal'), ('exact', 'Exact'), ('percentage', 'Percentage'), ('shares', 'Shares')], default='equal', max_length=10)),
                ('receipt_urls', models.JSONField(blank=True, default=list)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to='users.user')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
